### ISSUE TITLE
Umsetzung Screens

### ISSUE THREAD

**Issue by Madoka03** [Snapstromegon/TH-SS19-WD-Projekt#4]
Die auf Basis der Wireframes #1 entstandenen Screens #2 in HTML und CSS umsetzen.

Mobil
- [x] Galerie
- [x] Detailansicht mit Metainformationen
- [x] Vollbildansicht

Anpassung an größere Displays
- [x] Galerie
- [x] Detailansicht mit Metainformationen
- [x] Vollbildansicht

**Comment by Snapstromegon** [comment]
![Group](https://user-images.githubusercontent.com/18480654/62763799-b23c6100-ba8c-11e9-83a3-4784f5cdd6d9.png)
Hier einmal mit specs

**Comment by Snapstromegon** [comment]
![Group 2](https://user-images.githubusercontent.com/18480654/62764377-08f66a80-ba8e-11e9-86d7-6fab322b2dfd.png)
Fullscreen sollte sich ergeben

**Comment by Madoka03** [comment]
**ToDo Verbesserungen**
- [x] Kopfleiste im Template soll immer zu sehen sein.
- [x] Background Image durch img Tags ersetzen
- [x] position fixed durch Flexbox ersetzen

**Comment by Madoka03** [comment]
@Snapstromegon Wenn du noch Änderungswünsche am Template hast dann bitte hier posten, sonst closen wenn es so in Vue.js Components überführt werden kann.

**Comment by Snapstromegon** [comment]
@Madoka03 Im full.html stimmt die App Bar oben noch nicht (die Sachen stehen noch immer ganz am linken Rand) und aus der Flexbox main im details würde ich eventuell ein Grid machen, aber alles ist gut genug, dass ich das issue close
